### ISSUE TITLE
Does the MSP-EXP430FR5969 board work?

### ISSUE THREAD

**Issue by lihk** [rajeev1986/contikios-for-lora#2]
Now, the available board with msp430 MCU is MSP-EXP430FR5969, but i'm not sure whether the codes here can be compiled and ran on this board. The detailed description of this board can be found in the following link:  http://www.ti.com/lit/ug/slau535b/slau535b.pdf. I will appreciate it if you could give me some reference.

**Comment by rajeev1986** [comment]
@lihk 
The current port is for MSP-EXP430FR5969 MCU and these codes have been compiled and tested on the actual hardware. However, the board on which these codes were tested was custom designed but the MCU is the same with SX1276 LoRa radio chip. These codes can also be executed on EXP430FR5969 launchpad provided that the SPI interface is correctly wired for the LoRa. To utilize leds on the launchpad, one will have to reconfigure the leds ports in the Contiki driver.
More details can be found [here](https://contikios4lora.github.io/contikios-lora/) and [here](http://www.rajeevpiyare.com/wp-content/uploads/2018/09/view.pdf).
