### ISSUE TITLE
Wake up Receiver

### ISSUE THREAD

**Issue by nkaramolegos** [rajeev1986/contikios-for-lora#3]
Hello, can you please explain me the usage of WuRX? As I understand you developed the driver for the SX1276 based on Contiki. Therefore, it is possible to run RPL or UDP using your LoRa driver?

**Comment by rajeev1986** [comment]
Hi. To understand the usage and advantage of WuRX, please refer to the following articles:

1. [On-Demand LoRa: Asynchronous TDMA for Energy Efficient and Low Latency Communication in IoT](https://www.rajeevpiyare.com/publications/sensors-18-03718.pdf)
2. [On-Demand TDMA for Energy Efficient Data Collection with LoRa and Wake-up Receiver](https://www.rajeevpiyare.com/publications/on-demand-tdma.pdf)
3. [KRATOS: An Open Source Hardware-Software Platform for Rapid Research in LPWANs](https://www.rajeevpiyare.com/publications/kratos.pdf)

Yes, the Sx1276 driver is implemented in ContikiOS. However, the current software has only been tested with Contiki Collect atop LoRa. The RPL has not been tested and might even work. :) Nevertheless, the driver is compatible and might need minor changes or enhancements to make RPL fully work.

This is the reason why we have made our software open-source where developers can enhance and implement new features.
Hope this helps....
